### PR TITLE
Adding an "inc" command to the RpcHandler for autonomous increments.

### PR DESCRIPTION
**Pull request by KevinOrtman**
Hi tsuna,
I've added an "inc" command to the RpcHandler for autonomous increments, based very heavily on the code for the "put" command.  It requires a slight modification to asynchbase to support Deffered<Object> returns from the HBaseClient.atomicIncrement() calls.  

I added an override to HBaseClient to support those and I will submit a pull request for that change as well.  The atomicIncrement override is a bit sloppy (just added a boolen value to the method signature) but it works, maybe a different method name would be more elegant? 

Either way, the code change has been running under fairly heavy load on our live environment and is working very well.

### CODE REVIEW

**Comment by tsuna** [comment]
After re-reading your change, I realized that it's doing a counter increment directly on the timestamp passed in the call.  For instance:

```
inc my.metric 1234567890 1 host=foo
inc my.metric 1234567891 1 host=foo
inc my.metric 1234567892 1 host=foo
```

Will lead to just having `[1, 1, 1]` for each of the 3 timestamps.  This essentially means that we're incrementing "one second buckets".  Does that assume that the collector will round down the timestamp to a certain boundary, e.g. round it down to a 10s boundary, or a 60s boundary, to effectively widen the bucket?  Or are you relying on downsampling with the "sum" function?

What sort of collector did you write that use this? (I assume that if you use tcollector you also had to patch it to understand the `inc` verb?)

What I had in mind was something along the lines of:
- When we get a counter increment for a particular metric, we increment **a** counter in HBase.
- Periodically (maybe every 10s or every 15s?) we read the value of the counter and store it in HBase, just like we'd store a regular datapoint.

So when you have something like this come in: `inc my.metric 1234567890 1 host=foo` what you'd do is increment the value of, say, `row=[my.metric, timestamp: 0, host=foo]`.  We will always increment this counter for this combination of metric/tags.  The increment operation returns the value post-increment, and we could attach a `Deferred` to it every once in a while to store that value in HBase.

But maybe we can have both use-cases.  Maybe we can support your use-case and also a variant of the `inc` verb that could look like something like this:

```
inc 10 my.metric 1234567890 1 host=foo
inc 10 my.metric 1234567891 1 host=foo
inc 10 my.metric 1234567892 1 host=foo
```

Where the `10` would mean "I want the value of this counter stored in HBase every 10 seconds".  So in this example we'd end up with just one data point, value 3, at time 1234567890.

What do you think?

PS: In the future please send your pull request upstream (to the OpenTSDB project, not my own fork).  No worries for this time.

**Comment by KevinOrtman** [comment]
Hi Tsuna,Thank you for considering this pull, it is greatly appreciated by our folks here at CSG.  Your analysis is correct, we are doing the rounding prior to submit to OpenTSDB, incrementing in x second buckets.
In our case, we are dealing with transaction counters.  One example would be our mainframe system which processes hundreds of millions of transactions daily.  We have a process in each batch running in each lpar that records every transaction (60+ processes).  When any one of those process records at least 500 transactions, it sends all 500 transactions to our aggregator, this push from the mainframe happens every 5 seconds for the low-volume batches, and may happen more than once a second for high-volume batches.  An example of the data looks similar to this:

1234567890 xaction=retcust batch=PQTD cust=ABC loc=terma
1234567890 xaction=retcust batch=PQTD cust=ABC loc=termb
1234567890 xaction=retcust batch=PQTD cust=ABC loc=termb
1234567890 xaction=retcust batch=PQTD cust=ABC loc=terma
1234567891 xaction=order batch=PQTD cust=ABC loc=termz
1234567891 xaction=updcust batch=PQTD cust=ABC loc=termy
1234567891 xaction=retcust batch=PQTD cust=ABC loc=termq
1234567891 xaction=retcust batch=PQTD cust=ABC loc=terma

Our aggregator reads all 500 records, and counts the number of unique records in that group for a given downsample period (i.e. 1 minute), to create something like this in memory (assuming 1234567890 is the lower bound of a 10 second bucket):

my.metric 1234567890 2 xaction=retcust batch=PQTD cust=ABC loc=terma
my.metric 1234567890 2 xaction=retcust batch=PQTD cust=ABC loc=termb
my.metric 1234567890 1 xaction=order batch=PQTD cust=ABC loc=termz...

Now that it's aggregated, I have to make a decision.  I know that the next 500 records I receive from batch=PQDT will probably have similar xactions executed by the same cust/loc combination for the same 1 minute period.  I could spawn a thread, store all data for that 1 minute period in memory or on the local filesystem and periodically flush to OpenTSDB after I'm certain I will no longer receive data for that period, but that limits me to a single aggregator and inhibits scale-out & redundancy... I could flush the information to a distributed memory cache or intermediate db like redis as long as it supports atomic transactions or locking to allow me to scale aggregators... there are other options as well.  But in our case, we simply "inc" to OpenTSDB all metrics received during that batch, downsampled to x seconds and allow OpenTSDB/asynchbase/HBase sort it out for us, and it's been working great.

That's just one use case, but I've seen others in this thread (millisecond recordings from hardware).

In the second use case you presented, I love what you have outlined.  It basically takes care of the housekeeping I'm doing in my aggregator and encapsulates that into OpenTSDB proper.  This would certainly eliminate the need for most of the logic I have in that tier (I'm still translating the EBCDIC/binary transaction logs into metrics with name/value pairs), and I'm sure it would help a lot of folks out.

There are still use cases where it makes sense to "externalize" the downsampling to allow the caller to have ultimate control over what's happening & fortunately that use case is the simplest to implement.  If you are on board, implementation of both strategies would be awesome.  I'm happy to help in any way, if you would like - just let me know.

Thanks,Kevin 
PS Sorry bout the pull request to private, next time I will target the main project.

**Comment by tsuna** [comment]
What do you think about the syntax I proposed for the second form of `inc`?

```
inc 10 my.metric 1234567890 1 host=foo
inc 10 my.metric 1234567891 1 host=foo
inc 10 my.metric 1234567892 1 host=foo
```

**Comment by KevinOrtman** [comment]
Hi Tsuna, That would be great.  If I would like to use functionality similar to what I have today, I would simply do the following, right?

inc 0 my.metric 1234567890 1 host=foo
inc 0 my.metric 1234567891 1 host=foo
inc 0 my.metric 1234567892 1 host=foo

That would inc the existing value in HBase without performing aggregation at the OpenTSDB level?

**Comment by tsuna** [comment]
No, `inc 0 my.metric ...` wouldn't be the same thing as `inc my.metric ...`.

The former will first update a global counter, and then store the value of that counter in a cell at the current time. The latter will just increment the value of the cell at the current time.

So the difference is that in the first case you have a monotonically increasing counter, whereas in the second case your counter resets to 0 at every "bucket".

I am also realizing that in the former case of having a global, monotonically increasing counter, it doesn't make sense to pass a timestamp in the request, e.g. what happens if we get these two calls, on two different TSDs:

```
inc 10 my.metric 2000000000 4 host=foo  // Sent to TSD 2
inc 10 my.metric 1000000000 5 host=foo  // Sent to TSD 1
```

TSD1 would increment the global counter by 4, and then store the resulting value of the global counter at time 2000000000.  Then TSD2 would increment the global counter by 5 and then store the resulting value at time 1000000000.  But it doesn't really make sense to store a newer value of the counter at an older timestamp.

So maybe this form of the call, with the global counter, should be without a timestamp, as it only makes sense to have the TSD timestamp the value with "now".

Whereas in your form of the call, it makes sense to pass a timestamp, because it's the client that decides which "1s bucket" gets incremented.

Does that make sense?

**Comment by KevinOrtman** [comment]
Tsuna, that does make sense and it's awesome.
So, either of these would be valid, right?

inc 10 my.metric 4 host=foo  // increments the value of my.metric in the 10s bucket by 4
inc my.metric 2000000000 4 host=foo  // increments the value of my.metric @ timestamp 2000000000 by 4.

Should the calling patterns be mutually exclusive to prevent global counter vs live update nastiness?    if (global counter exists) then error on call_pattern_2
What happens if these two calls are received in consecutive order?  Two global counters with different resolutions where the lower resolution (10s) includes the higher?

inc 10 my.metric 4 host=foo
inc 5 my.metric 3 host=foo 

I'm also wondering if there are opportunities for efficiency gains in terms of # cols/compactions if metric buckets are pre-specified during metric creation or as post-op...
Not trying to make this harder, just providing food for thought to help you flesh this out.  ;)

**Comment by tsuna** [comment]
In your first example, the first `inc 10 ..` would do a global increment and store the new current value at a 10s boundary, the second `inc my.metric 2000000000 ..` would only increment the cell for the value of my.metric at time 2000000000.

Maybe we should have the ability to configure a metric as being either a global counter or a manually-bucketed counter, however right now there is no mechanism to store such additional metadata per metric.  But there is already code to do this in Chris's Scratch fork, and this is a functionality that we need upstream anyway, so it'll happen, but that would mean we can't implement this feature until we have the metadata code in place.

In your second example, the first `inc 10 ..` would increment the global counter and store the new value at a 10s boundary, the second `inc 5 ..` would increment the global counter again and store the new value at a 5s boundary.  This may lead to weird results, especially if you did the `inc 5 ..` first and then the `inc 10 ..` second, because you could end up with a data point earlier (at a 10s boundary) that has a smaller counter than the one at the 5s boundary.  Obviously the 5/10 interval is only in the query because we don't have the ability to store per-metric metadata, again.

I'm also thinking it may be better to use two different verbs for the two kinds of counters, to prevent some confusion.  We need a verb for the global counter increments, and one for the bucketed counter increments.  Any suggestion?  I'm tempted to keep `inc` for global increments, but don't have a great idea for a name for the bucketed ones.

**Comment by KevinOrtman** [comment]
How's this?    inc - global increments    add - bucketed counter inc
Or    count - global increment    inc - bucketed counter

**Comment by tsuna** [comment]
I like `inc` and `add`.  It seems intuitive that `inc` increments some counter, whereas `add` simply adds a delta to a specific data point.

**Comment by KevinOrtman** [comment]
Should I go ahead and send a pull request to the `next` branch in the main repository for the `add` operator?  That's the simple case and we already have the code to make it happen.  

The only requirement would be adding a method overload to the asynchbase to support a deferred object return from AtomicIncrement.

**Comment by jakeri** [comment]
Waking up an old thread. :-)
This change did not end up in official OpenTSDB library right?

Would love to see this.

**Comment by KevinOrtman** [comment]
bump

—

**Pull request closed without merging**
